blank_issues_enabled: false
contact_links:
  - name: Community Chat
    url: https://openui5.slack.com/archives/CSQEJ2J04
    about: A dedicated slack channel for our community. If you are not part of the OpenUI5 Slack Workspace yet, you can invite yourself via https://ui5-slack-invite.cfapps.eu10.hana.ondemand.com.
  - name: Questions
    url: https://github.com/SAP/ui5-webcomponents-react/discussions
    about: Please ask and answer questions here.
