name: 'Issue Comments'

on:
  workflow_dispatch:

jobs:
  issue-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install Dependencies
        run: |
          yarn install --immutable
          yarn add @octokit/rest@v19.0.13 @octokit/auth-app@v5.0.4

      ### Semantic Release Bot comments for issues and PRs ###
      - name: Add release comments to issues and PRs
        uses: actions/github-script@v6
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          script: |
            const { default: addIssueComments } = await import('${{ github.workspace }}/.github/createIssueCommentsForRelease.mjs');

            await addIssueComments({ github: github.rest, context })
